Improve handling of stderr output
davidfowl/Micronetes pull request #41
Opened 2020-01-23 08:45 UTC by nj0yeh

Improve handling of stderr output.

Write correct error message when the build fails.

2020-01-23 09:42 UTC, davidfowl commented
2 things:
- Take a look at this PR that just went in https://github.com/davidfowl/Micronetes/commit/afe111b06c73c2360cad8055f367037be5ec710f
- Redo the commits to be based on master without all the merges.

2020-01-23 09:49 UTC, nj0yeh commented
>     * Take a look at this PR that just went in [afe111b](https://github.com/davidfowl/Micronetes/commit/afe111b06c73c2360cad8055f367037be5ec710f)

I am aware of it and talked to the author. I think my solution is a little bit cleaner (and it solves the error of not displaying the build error messages).

>     * Redo the commits to be based on master without all the merges.

Done.

2020-01-23 09:57 UTC, davidfowl commented
> I am aware of it and talked to the author. I think my solution is a little bit cleaner 

From an API POV sure but it doesn't change the experience, the output is interleaved into a single output stream. The previous solution does this by default so all process launches were capturing both stdout and error. This only turns it back on for process launches for the project executable.

> (and it solves the error of not displaying the build error messages).

Yep this PR has 2 different changes.

2020-01-23 17:02 UTC, davidfowl commented on src/Micronetes.Hosting/Infrastructure/ProcessUtil.cs
> -                        if (outputDataReceived != null)
I think the logic should put everything in output data unless error data is specified. By default there's no value is splitting the streams here.

2020-01-23 17:02 UTC, davidfowl commented on src/Micronetes.Hosting/ProcessRunner.cs
> +                                                 errorDataReceived: data => service.Logs.OnNext(data),
Then we can also undo this.

2020-01-23 17:02 UTC, davidfowl commented on src/Micronetes.Hosting/ProcessRunner.cs
> +                            errorDataReceived: data => service.Logs.OnNext($"[{replica}]: {data}"),
And this.

2020-01-23 17:03 UTC, davidfowl requested changes
Made a couple comments

2020-01-24 06:15 UTC, davidfowl approved these changes

2020-01-24 06:45 UTC, merged